---
Name: campaignmonitor
Before: 'mysite/*'
After: 'framework/*','cms/*'
---


Member:
  extensions:
    - CampaignMonitorMemberDOD

CampaignMonitorMemberDOD:
  campaign_monitor_signup_fieldname: "CampaignMonitorSubscriptions"
