---
Name: campaignmonitor
Before: 'app/*'
After: 'framework/*','cms/*'
---


SilverStripe\Security\Member:
  extensions:
    - CampaignMonitorMemberDOD

CampaignMonitorMemberDOD:
  campaign_monitor_signup_fieldname: "CampaignMonitorSubscriptions"
