---
Name: campaignmonitor
Before: 'app/*'
After: 'framework/*','cms/*'
---
SilverStripe\Security\Member:
  extensions:
    - Sunnysideup\CampaignMonitor\Decorators\CampaignMonitorMemberDOD
Sunnysideup\CampaignMonitor\Decorators\CampaignMonitorMemberDOD:
  campaign_monitor_signup_fieldname: CampaignMonitorSubscriptions
